name: DfT.ZEV.Common (Pull request)

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'src/common/**'
      - '!README.md'
      - '!**/README.MD'

defaults:
  run:
    working-directory: ./src/common

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: |
        cd DfT.ZEV.Common && make build
        cd ..
        cd DfT.ZEV.Common.MVC.Authentication && make build