name: DfT.ZEV.Services.Functions.Notifications (Release)

on:
  push:
    branches:
      - release/**
    paths:
      - 'src/services/functions/notifications/DfT.ZEV.Services.Notifications.Handler/**'
      - '!README.md'
      - '!**/README.MD'

env:
    DEPLOY_ENVIRONMENT: release
    SOURCE_COMMIT_HASH: ${{ github.sha }}
    TF_VAR_SOURCE_COMMIT_HASH: ${{ github.sha }}

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/services/functions/notifications/DfT.ZEV.Services.Notifications.Handler
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: make build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/terraform/04-functions/04-03-notifications-function
    steps:
    - uses: actions/checkout@v2
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.RELEASE_GOOGLE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.3

    - name: Terraform init
      run: make init

    - name: Deploy
      run: make apply-auto-approve
