name: DfT.ZEV.Services.Functions.ComplianceCalculator (Pull request)

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'src/services/functions/compliance-calculation/**'
      - 'src/common/**'
      - 'src/core/**'
      - '!README.md'
      - '!**/README.MD'

defaults:
  run:
    working-directory: ./src/services/functions/compliance-calculation/DfT.ZEV.Services.ComplianceCalculation.Handler

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Postgres Database
      working-directory: .
      run: docker compose -f infrastructure/docker/docker-compose.yml up -d

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: make build

    - name: Test with coverage
      run: make test-coverage
