name: DfT.ZEV (Pull request)

on:
  pull_request:
    branches: [ develop ]
    paths:
      - '!README.md'
      - '!**/README.MD'
      - '**/**.cs'
      - '**/**.json'

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Postgres Database
      run: docker compose -f infrastructure/docker/docker-compose.yml up -d

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: make build-test
