name: DfT.ZEV.Services.Websites.ManufacturerReview (Push)

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - hotfix/**
    paths:
      - 'src/services/websites/manufacturer-data-review-portal/**'
      - 'src/common/**'
      - 'src/core/**'
      - '!README.md'
      - '!**/README.MD'

env:
  DEPLOY_ENVIRONMENT: dev
  TF_VAR_source_commit_hash: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/services/websites/manufacturer-data-review-portal
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: make build

    - name: Test with coverage
      run: make test-coverage

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure/terraform/05-websites/05-02-manufacturer-website
    steps:
    - uses: actions/checkout@v2
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.3

    - name: Authenticate against docker registry
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Terraform init
      run: make init

    - name: Deploy
      run: terraform apply -var-file="../../configuration/environments/dev.tfvars"