name: DfT.ZEV.Services.Websites.ManufacturerReview (Pull request)

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'src/services/websites/manufacturer-data-review-portal/**'
      - 'src/common/**'
      - 'src/core/**'
      - '!README.md'
      - '!**/README.MD'

defaults:
  run:
    working-directory: ./src/services/websites/manufacturer-data-review-portal

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: make build

    - name: Test with coverage
      run: make test-coverage