name: DfT.ZEV.Services.APIs.SchemeData (Push)

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'src/services/apis/scheme-data/DfT.ZEV.Services.SchemeData.Api/**'
      - 'src/common/**'
      - 'src/core/**'
      - '!README.md'
      - '!**/README.MD'

env:
    DEPLOY_ENVIRONMENT: dev
    SOURCE_COMMIT_HASH: ${{ github.sha }}
    TF_VAR_SOURCE_COMMIT_HASH: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: ./src/services/apis/scheme-data/DfT.ZEV.Services.SchemeData.Api
    steps:
    - uses: actions/checkout@v4

    - name: Setup Postgres Database
      working-directory: .
      run: docker compose -f infrastructure/docker/docker-compose.yml up -d

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: make build

    - name: Test with coverage
      run: make test-coverage

    - name: Build docker image
      run: make docker-build

    - name: Build docker image
      run: make docker-push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    working-directory: ./infrastructure/terraform/03-apis/03-02-scheme-data-api
    steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.3

    - name: Terraform init
      run: make init

    - name: Deploy
      run: make apply-auto-approve
